test_task: 
 feature_order: ['features/featureOne', 'features/featureTwo', 'features/featureThree']
 runtime_defaults:
  environment: 'release'
  log_level: 'debug'
  format: 'pretty'
 defaults: ['--format html', '--out coverage/report.html', '-P -s']